# -*- coding: utf-8 -*-
"""Unsupervised_Learning_Example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J__5xgHSKzSs2_ZICr7q8NN4VEApCaEN
"""

import os
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from PIL import Image

# Load and preprocess images
def load_images_from_folder(folder_path, img_size=(64, 64)):
    images = []
    labels = []
    label_map = {'city_car': 0, 'sign_board': 1, 'traffic_light': 2}

    for label_name in os.listdir(folder_path):
        class_path = os.path.join(folder_path, label_name)
        if not os.path.isdir(class_path):
            continue
        for filename in os.listdir(class_path):
            img_path = os.path.join(class_path, filename)
            try:
                img = Image.open(img_path).convert("RGB").resize(img_size)
                img_array = np.array(img).flatten()
                images.append(img_array)
                labels.append(label_map[label_name])
            except Exception as e:
                print(f"Error loading {img_path}: {e}")

    return np.array(images), np.array(labels)

# Dataset path
image_dir = "dataset_traffic_light/traffic_light/data/train"

# Load and scale image data
X, y = load_images_from_folder(image_dir)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Apply PCA for visualization
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

# Apply KMeans clustering
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
kmeans.fit(X_scaled)
cluster_labels = kmeans.labels_

# Visualize clustering results
plt.figure(figsize=(8, 6))
plt.scatter(X_pca[:, 0], X_pca[:, 1], c=cluster_labels, cmap='viridis')
plt.title("K-Means Clustering of Transport Images")
plt.xlabel("PCA Component 1")
plt.ylabel("PCA Component 2")
plt.colorbar(label='Cluster ID')
plt.grid(True)
plt.show()

# Display one image from each class
def display_sample_images(image_dir):
    fig, axs = plt.subplots(1, 3, figsize=(12, 4))
    class_names = ['city_car', 'sign_board', 'traffic_light']
    for i, class_name in enumerate(class_names):
        class_folder = os.path.join(image_dir, class_name)
        sample_image_path = os.path.join(class_folder, os.listdir(class_folder)[60])
        image = Image.open(sample_image_path).resize((64, 64))
        axs[i].imshow(image)
        axs[i].axis('off')
        axs[i].set_title(class_name)
    plt.suptitle("One Sample Image from Each Class")
    plt.show()

display_sample_images(image_dir)

